version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@db:5432/mydb"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
       - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_bun_modules:/app/node_modules
    environment:
      VITE_BACKEND_API_URL: "http://localhost:3000"
    command: bun run dev --host 0.0.0.0

volumes:
  db_data:
  backend_node_modules:
  frontend_bun_modules:
